### ISSUE TITLE
Split out page content into React components

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/councildataproject.github.io#13]
Instead of having all the content in App.js, make Hero, About, Step List, Instance Container, etc components.

**Comment by KieniL** [comment]
I would like to work on that

**Comment by JacksonMaxfield** [comment]
Awesome! Feel free to work in a fork of the repo and make a PR whenever you feel it's ready.

Thank you so much.

P.S. Mind letting me know how you found the project?

**Comment by JacksonMaxfield** [comment]
Resolved by #15
