### ISSUE TITLE
Allow navigation to be constructed with props

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/councildataproject.github.io#16]
The navigation component is currently constructed with a [static object](https://github.com/CouncilDataProject/councildataproject.github.io/blob/main/src/components/layout/Navigation.js#L3).

Would be great to move that object to prop definition and then pass it in from App.js.

**Comment by codyveladev** [comment]
I can get this done

**Comment by JacksonMaxfield** [comment]
Resolves #18
