### ISSUE TITLE
Make instances a collection of Instance components

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/councildataproject.github.io#17]
Currently all instance cards live as raw HTML in the [instances](https://github.com/CouncilDataProject/councildataproject.github.io/blob/main/src/components/layout/Instances.js) component, but it would be nice to be able to just provide a list of objects to the component and have it construct each element for us. Likely this would mean making an `Instance` component and mapping across the provided object as a prop.

**Comment by RivaD2** [comment]
Hi there Jackson,
 I would love to help you out with this issue!  If it is up for grabs, I will gladly take it off your hands.

**Comment by JacksonMaxfield** [comment]
Hey! Would gladly accept the help. Feel free to fork and PR 🙂

**Comment by RivaD2** [comment]
Perfect! Thank you for letting me take this on. :)

**Comment by JacksonMaxfield** [comment]
Closed by #21
