### ISSUE TITLE
Add a search bar / some filter options to the Locations section.

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/councildataproject.github.io#44]
As more and more CDP instances are deployed, the list becomes slightly annoying to scroll all the way through.

It would be nice to have a search bar / some filtering (maybe by region or level of gov??) to reduce the number of locations shown at any given time.

We can also paginate the locations as well.

Link to section: https://councildataproject.org/#locations
Screenshot: 
![image](https://user-images.githubusercontent.com/17132317/225084598-2c397240-8c59-4a6d-91bc-8984c80affdd.png)
(the locations section is just really really long)

**Comment by martinyis** [comment]
Hey, I would like to work on that, could you assign it to me if possible?

**Comment by evamaxfield** [comment]
Hey! Thanks!

**Comment by evamaxfield** [comment]
@martinyis it's live and it works great! Thank you so much!! Going to reopen in the hope that someone comes along and adds a search bar in the future -- the region selector is a great start.

**Comment by martinyis** [comment]
Hey, I would like to add a search bar as well. Assign it to me if possible!

**Comment by evamaxfield** [comment]
Thanks @martinyis! It looks like it is still assigned actually!

**Comment by evamaxfield** [comment]
Thanks again @martinyis both of those were incredibly fast fixes! I appreciate it.

**Comment by evamaxfield** [comment]
If you are ever interested in taking on issues in the web application itself free to head on over to https://github.com/CouncilDataProject/cdp-frontend/issues
